### ISSUE TITLE
Enable sitemap plugin

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/github-markup-example#2]
It would be good if we can enable the jekyll sitemap plugin on this site, then we could use that with BMUSE to harvest all the pages on the site.

**Comment by ljgarcia** [comment]
Done, I add the sitemap and the robots files. I will add this to the tutorial and it would be nice to add the BMUSE part as well so we connect it with the following part of the tutorial. Discussion point for our meeting
